version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "personal-website-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1xxnf2ksmwtwm"
s3_prefix = "personal-website-api"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
